sudo: required
services:
    - docker

before_install:
    - docker build -t jasonosborne/complex-test -f ./client/Dockerfile.dev ./client
script:
    - docker run -e CI=true jasonosborne/complex-test npm test -- --coverage
after_success:
    -docker build -t JASONOSBORNE/multi-client ./client
    -docker build -t JASONOSBORNE/multi-server ./server
    -docker build -t JASONOSBORNE/nginx ./nginx
    -docker build -t JASONOSBORNE/multi-worker ./worker

    # Docker login & push to hub
script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push JASONOSBORNE/multi-client
    - docker push JASONOSBORNE/multi-nginx
    - docker push JASONOSBORNE/multi-server
    - docker push JASONOSBORNE/multi-worker
# deploy:
#     edge: true
#     provider: elasticbeanstalk
#     region: "us-west-2"
#     app: "docker-react"
#     env: "DockerReact-env"
#     bucket_name: 
#     bucket_path: "docker-react"
#     on:
#         branch: master
#     access_key_id: $AWS_ACCESS_KEY
#     secret_access_key: 
#         secure: $AWS_SECRET_KEY